### ISSUE TITLE
EasyChartX issues

### ISSUE THREAD

**Issue by fujiajin** [SeeSharpOpenSource/SeeSharpTools#1]
EasyChartX的Plot方法类型S只支持 float/int/uint/short/ushort，对于实时曲线来说，通常X轴会是时间，这样就无法使用了么？能不能加一层重载？

**Comment by JYTEK-Admin** [comment]
你好，目前这版还没有考虑加入这个功能。如果你有需要的话暂时可以使用StripChartX实现类似的功能(该控件支持时间显示)。我们在下个版本需要讨论下是否添加这个需求。

**Comment by JYTEK-Admin** [comment]
下个版本讨论是否更新

**Comment by JYTEK-Admin** [comment]
下个版本讨论是否实现
